module.exports.setup = function(app, basePath = "api", version = "v0") {
    var path = `/${basePath}` //todo add version
    var userRoutes = require('./routes/userRoutes')
    var buildingRoutes = require('./routes/buildingRoutes')
    var memberRoutes = require('./routes/memberRoutes')
    var binRoutes = require('./routes/binRoutes')
    var cityRoutes = require('./routes/cityRoutes')
    var trashRoutes = require('./routes/trashRoutes')
    var trashCategoryRoutes = require('./routes/trashCategoryRoutes')
    var rankRoutes = require('./routes/rankRoutes')
    var rewardRoutes = require('./routes/rewardRoutes')
    app.use(path, userRoutes)
    app.use(path, buildingRoutes)
    app.use(path, memberRoutes)
    app.use(path, binRoutes)
    app.use(path, cityRoutes)
    app.use(path, trashRoutes)
    app.use(path, trashCategoryRoutes)
    app.use(path, rankRoutes)
    app.use(path, rewardRoutes)
}